version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    
    working_directory: ~/repo

    steps:
      - run: echo build step
      - run: mkdir build_output
      - run: touch build_output/compiled_output.txt
      - persist_to_workspace:
          root: build_output
          paths:
            - '*'
  
  test:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - run: echo test step,secret $MY_SECRET
      - attach_workspace:
          at: ~/repo/workspace
      - run: ls ~/repo/workspace/compiled_output.txt
             
  
  deploy:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - run: echo deploy step  
      - attach_workspace:
          at: ~/repo/workspace
      - run: ls ~/repo/workspace/compiled_output.txt
      
workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - master  
  perf-tests:
    jobs:
      - perf-testing
    triggers:
      - schedule:
          cron: "15 2 * * *"
          filters:
            branches:
              only:
                - master  


            