version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.10
    
    working_directory: ~/repo

    steps:
      - run: echo build step
      - run: exit 1
  
  test:
    docker:
      - image: circleci/node:4.10

    working_directory: ~/repo

    steps:
      - run: echo test step  


workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
